spring:
  profiles:
    active: dev
  application:
    name: xzm-agent

  ai:
    mcp:
      client:
        enabled: false
        sse:
          connections:
            server1:
              url: http://localhost:8127
    openai:
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-v4-flash # 可选 deepseek‑reasoner(R1) / deepseek‑v3
          temperature: 0.7
      embedding:
        model: deepseek-v4-flash
        options:
          model: deepseek-v4-flash
#   临时注释掉，便于大家开发调试和部署（实际需要启动 MCP 服务）



  datasource:
    # 主数据源 - MySQL
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/xzmagent?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
    # 从数据源 - PostgreSQL
    pg:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://pgm-bp196102bt46j0pnoo.pg.rds.aliyuncs.com/xzm-agent
      username: xzm
      password: Xiaomo1994
mybatis‑plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper‑locations: classpath:mapper/**/*.xml

server:
  port: 8888
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.yuaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    io.modelcontextprotocol: DEBUG   # MCP 客户端协议层（能看到 tools/list 请求和响应）
    org.springframework.ai: DEBUG    # Spring AI 工具注册层